[package]
name = "indemnify"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
solana-sdk = "1.8.1"

[dependencies]
solana-program = "1.9.5"